version: "3.7"

services:
  database:
    image: postgres:12.3-alpine
    restart: always
    container_name: conectiong-db
    hostname: database
    networks:
      - internal_network
    environment:
      - "POSTGRES_USER=veloss"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_DB=connecting"
    command: ["-p", "5432"]
    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgsql-data:/var/lib/postgresql/data

  server:
    build: "."
    restart: always
    privileged: false
    container_name: connecting-server
    networks:
      - internal_network
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=host.docker.internal
    volumes:
      - ./ ./

networks:
  internal_network:

volumes:
  pgsql-data:
